#!/usr/bin/env bash

cd "$(dirname "$(realpath "$0")")"

# 3K model settings
prefered_resolution="2880x1800"
refresh_rate="120.00"
ui_scale=1.7475727796554565 # 1.75
y_offset=1030
backlight=card1-eDP-2-backlight

# 1080p model settings (Uncomment if needed)
#prefered_resolution="1920x1200"
#refresh_rate="60.00"
#backlight=card1-eDP-2-backlight
#ui_scale=1
#y_offset=1200

function suenv {
  sudo /usr/bin/env "$@"
}

function external-display-connected {
    [ "$(xrandr --listmonitors | grep -v 'eDP' | wc -l)" -gt 1 ]
}

function active-external-displays {
    xrandr --query | grep " connected" | grep -vE 'eDP-[12]' | awk '{print $1}'
}

case "$1" in
  watch-displays)
    while inotifywait -e attrib /dev/bus/usb/*/ ; do
      if ! external-display-connected; then
        "$0" normal
      fi
    done
    ;;
  set-displays)
    sleep 1
    if ! external-display-connected; then 
      "$0" normal
    fi
    ;;
  normal|bottom-up)
    if lsusb | grep 0b05:1b2c ; then
      "$0" top
    else
      "$0" both
    fi
    ;;
  top)
    xrandr --output eDP-1 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --pos 0x0
    ;;
  both)
    xrandr --output eDP-1 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --pos 0x0 \
           --output eDP-2 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --pos 0x$y_offset --below eDP-1
    ;;
  bottom)
    xrandr --output eDP-2 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --pos 0x0
    ;;
  left-up)
    xrandr --output eDP-2 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --rotate left --pos 0x0 \
           --output eDP-1 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --rotate left --pos ${y_offset}x0
    ;;
  right-up)
    xrandr --output eDP-1 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --rotate right --pos 0x0 \
           --output eDP-2 --mode $prefered_resolution --rate $refresh_rate --scale $ui_scale --rotate right --pos ${y_offset}x0
    ;;
  status-internal)
    internal_monitors="$(xrandr --query | grep -E " connected " | grep -E "eDP-[12]")"
    case "$(echo "$internal_monitors" | wc -l)" in
      0) echo "none" ;;
      1) case "$(echo "$internal_monitors")" in
           *eDP-1*) echo "top" ;;
           *eDP-2*) echo "bottom" ;;
         esac ;;
      2) echo "both" ;;
    esac
    ;;
  status)
    (
      active-external-displays
    ) | grep -vE "^$" | sed -z "s/\n/+/g"
    "$0" status-internal
    ;;
  toggle)
    if xrandr --query | grep " disconnected" | grep eDP > /dev/null; then
      "$0" both
    else
      "$0" top
    fi
    ;;
  set-tablet-mapping)
    for type in tablets touchscreens; do
      dconf write "/org/gnome/desktop/peripherals/${type}/04f3:425b/output" "['eDP-1']"
      dconf write "/org/gnome/desktop/peripherals/${type}/04f3:425a/output" "['eDP-2']"
    done
    ;;
  toggle-bottom-touch)
    path="/org/gnome/desktop/peripherals/touchscreens/04f3:425a/output"
    if [ -z "$(dconf read "$path")" ]; then
      dconf write "$path" "['eDP-2']"
    else
      dconf reset "$path"
    fi
    ;;
  bat-limit)
    echo "${2:-80}" | suenv tee /sys/class/power_supply/BAT0/charge_control_end_threshold
    ;;
  sync-backlight)
    cat "/sys/class/backlight/intel_backlight/brightness" |
      suenv tee /sys/class/backlight/$backlight/brightness
    ;;
  set-kb-backlight)
    suenv python3 bk.py "$2"
    ;;
  watch-backlight)
    "$0" sync-backlight
    while inotifywait -e modify /sys/class/backlight/intel_backlight/brightness ; do
      "$0" sync-backlight
    done
    ;;
  watch-rotation)
    monitor-sensor --accel |
      stdbuf -oL grep orientation |
      stdbuf -oL cut -d: -f2 |
      stdbuf -oL sed 's/[ )]//g' |
      xargs -I '{}' stdbuf -oL "$0" '{}'
    ;;
  *) echo "Usage: duo <top|bottom|both|set-displays|toggle|status|set-tablet-mapping|bat-limit|sync-backlight|set-kb-backlight|watch-backlight|watch-rotation|watch-displays>"
esac
